/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayIdRouteImport } from './routes/play.$id'
import { Route as EditorIdRouteImport } from './routes/editor.$id'

const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayIdRoute = PlayIdRouteImport.update({
  id: '/play/$id',
  path: '/play/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorIdRoute = EditorIdRouteImport.update({
  id: '/editor/$id',
  path: '/editor/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/editor/$id': typeof EditorIdRoute
  '/play/$id': typeof PlayIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/editor/$id': typeof EditorIdRoute
  '/play/$id': typeof PlayIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/editor/$id': typeof EditorIdRoute
  '/play/$id': typeof PlayIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/docs' | '/editor/$id' | '/play/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/docs' | '/editor/$id' | '/play/$id'
  id: '__root__' | '/' | '/docs' | '/editor/$id' | '/play/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRoute
  EditorIdRoute: typeof EditorIdRoute
  PlayIdRoute: typeof PlayIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$id': {
      id: '/play/$id'
      path: '/play/$id'
      fullPath: '/play/$id'
      preLoaderRoute: typeof PlayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/$id': {
      id: '/editor/$id'
      path: '/editor/$id'
      fullPath: '/editor/$id'
      preLoaderRoute: typeof EditorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRoute,
  EditorIdRoute: EditorIdRoute,
  PlayIdRoute: PlayIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
